### ISSUE TITLE
500 error in  fleet web UI when query tab is clicked

### ISSUE THREAD

**Issue by cogmeta** [kolide/fleet#2037] opened 2019-04-26 18:48 UTC
### What version of `fleet` are you using (`fleet version --full`)?
fleet version 2.1.0

### What operating system are you using?
ubuntu

### What did you do?
launch a query in web UI

### What did you expect to see?
result of the query

### What did you see instead?
query progress indicator/spinner runs  forever..no result

**Comment by cogmeta** [comment] 2019-04-26 18:52
I am able to use launcher on three machines and i see hosts in the web UI

**Comment by cogmeta** [comment] 2019-04-26 18:55
on closer look, 
![Screen Shot 2019-04-27 at 12 24 38 AM](https://user-images.githubusercontent.com/10062479/56830047-f3fd1f00-6882-11e9-9a64-62ef1faa3208.png)
![Screen Shot 2019-04-27 at 12 24 22 AM](https://user-images.githubusercontent.com/10062479/56830049-f3fd1f00-6882-11e9-96ba-81d7ed44621a.png)
![Screen Shot 2019-04-27 at 12 24 18 AM](https://user-images.githubusercontent.com/10062479/56830051-f495b580-6882-11e9-87e1-657190e3b0b5.png)

**Comment by cogmeta** [comment] 2019-04-26 18:56
![image](https://user-images.githubusercontent.com/10062479/56830107-17c06500-6883-11e9-86f9-d720bab9da77.png)
![image](https://user-images.githubusercontent.com/10062479/56830120-20b13680-6883-11e9-8a6b-63599edb4dbb.png)

![image](https://user-images.githubusercontent.com/10062479/56830128-26a71780-6883-11e9-9335-50de021f1e02.png)

**Comment by zwass** [comment] 2019-04-29 02:47
Is this a new installation of Fleet or an upgrade from an earlier version? Have all the db migrations been run successfully (`fleet prepare db`)?

**Comment by zwass** [comment] 2019-05-24 18:17
Can you provide more information? If not I will close this issue as I don't have any way to reproduce.

**Comment by zwass** [comment] 2019-06-27 17:03
Closing due to inactivity and no way to reproduce.

**Closed as completed by zwass** 2019-06-27 17:03 UTC
