### ISSUE TITLE
Request error: certificate verify failed

### ISSUE THREAD

**Issue by hackdefendr** [kolide/fleet#2154] opened 2019-11-19 17:13 UTC
### What version of `fleet` are you using (`fleet version --full`)?
  fleet - version 2.3.0
  branch:       master
  revision:     bc9782e9b0c431ce8c24552861f5527fb0f4c390
  build date:   2019-08-14T18:55:06Z
  build user:   zwass
  go version:   go1.12.8

### What operating system are you using?
  Redhat 7

### What did you do?
Using our Certificate Authority, I generated an extended web server certificate that supports both Server and Client authentication. The fleet server starts up without issue, and shows a secure connection in Chrome. I imported my CA certificate into Redhat.

### What did you expect to see?
I expected to see my osquery agents connecting without issue.  Especially the local agent running on the same host as the fleet server is. This all worked flawlessly in development, but when we moved it to production it started failing.

### What did you see instead?
We are seeing a combination of connection errors from the client stating that the certificate verify process failed.  On the fleet server, the error says unknown certificate authority.

How do I troubleshoot this?

**Comment by hackdefendr** [comment] 2019-11-19 18:08
Additionally I have used openssl to verify the server certificate.

```
openssl verify -CAfile kirkland_ca.cer /var/osquery/server.pem
/var/osquery/server.pem: OK
```

So this makes no sense whatsoever.  The certificates are correct. The CA certificates are imported to the OS. Fleet says it is secure in Chrome. Why won't osquery agents connect? Even from the same host as fleet?

**Comment by zwass** [comment] 2019-11-19 19:03
Usually this sort of problem is resolved by including the full certificate chain in the PEM specified to osqueryd with `--tls_server_certs`. Please try that and let us know if it fixes your issue.

https://github.com/kolide/fleet/blob/master/docs/infrastructure/faq.md#how-do-i-fix-certificate-verify-failed-errors-from-osqueryd

**Comment by hackdefendr** [comment] 2019-11-21 14:50
I don't follow.  

I downloaded the PEM from the server like the instructions said, and placed that PEM in /var/osquery/.  I am already using --tls_server_certs in my osquery flag file.  I don't think fleet is using the correct CA path in Redhat, because both my CA and Intermediate certs are imported into the OS, and every other service see's that fine. Only fleet and osquery seem to ignore this.

The curl command suggested returns a Internal Server Error 500, but see's the certificate chain fine.

**Comment by hackdefendr** [comment] 2019-11-21 16:11
OK I created a PEM file using the server cert, the ca cert, and the intermediate cert.  Now I get this:

`Failed enrollment request to https://KOLIDESERVER:8080/api/v1/osquery/enroll (No node key returned from TLS enroll plugin) retrying...`

Not sure what that means.

**Comment by zwass** [comment] 2019-11-21 17:26
This would usually be caused by osquery sending an incorrect enroll secret. Use `--verbose --tls_dump` in your invocation of osquery so that you can see the back and forth communication with the Fleet server.

If you have further questions it's usually easiest to debug these things in #kolide on [osquery Slack](https://osquery-slack.herokuapp.com/).

**Comment by hackdefendr** [comment] 2019-11-21 21:53
Weird.  I guess the enroll key changed when I pushed the new PEM in place.

OK it is working now after creating a PEM file with the server cert, ca cert, and intermediate cert and then pushing that in place on both the server and the client.

I shouldn't have to create a bundled cert like that for signed certificates.

**Comment by zwass** [comment] 2019-11-22 00:59
IIRC whether osquery can use the system cert store depends on which platform you are running on. If you believe that requiring the full cert chain is a bug in osquery, please open an issue and that repo.

Glad you got your issue sorted :)

**Closed as completed by zwass** 2019-11-22 00:59 UTC

**Comment by linsihao7788** [comment] 2020-08-17 06:16
> Weird. I guess the enroll key changed when I pushed the new PEM in place.
> 
> OK it is working now after creating a PEM file with the server cert, ca cert, and intermediate cert and then pushing that in place on both the server and the client.
> 
> I shouldn't have to create a bundled cert like that for signed certificates.

Hi，

**Comment by linsihao7788** [comment] 2020-08-17 06:18
> Weird. I guess the enroll key changed when I pushed the new PEM in place.
> 
> OK it is working now after creating a PEM file with the server cert, ca cert, and intermediate cert and then pushing that in place on both the server and the client.
> 
> I shouldn't have to create a bundled cert like that for signed certificates.

Hello, I also met your problem, hint
Failed enrollment request to https://10.224.100.2:8080/api/v1/osquery/enroll (request error: certificate verify Failed) retrying...

How did you solve it?
