### ISSUE TITLE
Fleet is not able to connect to MySQL over SSL only with CA certificate specified

### ISSUE THREAD

**Issue by myfoxtail** [kolide/fleet#2124] opened 2019-10-31 00:37 UTC
I'm getting the following error message trying to run `fleet prepare db`:

```
Error creating db connection: register TLS config for mysql: load mysql client cert and key: open : no such file or directory
```

My config contains just a path to a CA certificate.

```
mysql:
        address: mydb.somewhere.com:3306
        database: kolide
        username: fleet
        password: teelf
        tls_ca: ./blah.crt.pem
        tls_config: true
```

It looks like it's trying to get client key and certificate files, but I don't need them in order to connect to the database. Is there any way to solve this problem?

**Comment by zwass** [comment] 2020-01-30 01:23
The `mysql_tls_ca` flag (https://github.com/kolide/fleet/blob/master/docs/infrastructure/configuring-the-fleet-binary.md#mysql_tls_ca) is intended to be used for client certificate auth, so Fleet expects you to provide a path to the client cert and key.

What are you trying to achieve?

**Comment by zwass** [comment] 2020-01-31 17:00
I'm going to close this issue as not a bug. If you need support you are best off asking on #kolide in osquery Slack. If you have a feature request, please open a new issue.

**Closed as completed by zwass** 2020-01-31 17:00 UTC
