### ISSUE TITLE
load react template: open frontend/templates/react.tmpl: file does not exist

### ISSUE THREAD

**Issue by anatol** [kolide/fleet#2156] opened 2019-11-30 17:58 UTC
### What version of `fleet` are you using (`fleet version --full`)?
2.4.0 built from sources using `make deps && make generate && make build`

### What operating system are you using?
Arch Linux

### What did you do?
run `fleet serve`

### What did you expect to see?
http://sever:8080 shows a valid web page.

### What did you see instead?
http text that says `load react template: open frontend/templates/react.tmpl: file does not exist`

I see this file mentioned in the fleet binary so it looks like the asset is packed correctly. But for some reason Server cannot find the asset.

```
$ grep -R react.tmpl            
server/service/frontend.go:		file, err := fs.Open("templates/react.tmpl")
.gitignore:frontend/templates/react.tmpl
Binary file build/binary-bundle/linux/fleet matches
Binary file build/fleet matches
webpack.config.js:    filename: '../frontend/templates/react.tmpl',
```

**Comment by anatol** [comment] 2020-01-25 19:57
Ping. Any update on this issue?

**Comment by zwass** [comment] 2020-01-27 18:32
Are you able to reproduce this on a fresh checkout of the repository? I'm not able to reproduce the issue, so it would be nice to try to narrow down what might be going on.

**Comment by zwass** [comment] 2020-02-06 17:17
I'm going to close this issue as I think it's likely a configuration problem and not a bug. Please reach out in #kolide on osquery Slack if you'd like help debugging.

**Closed as completed by zwass** 2020-02-06 17:17 UTC
Labels: Needs: Update
