### ISSUE TITLE
Unexpected EOF when pulling hosts

### ISSUE THREAD

**Issue by ccombs-sqsp** [kolide/fleet#2322] opened 2020-10-08 16:43 UTC
### What version of `fleet` are you using (`fleet version --full`)?
2.5.0
docker image kolide/fleet:2.5.0
### What operating system are you using?
linux

### What did you do?
From a configured fleetctl I ran:
`fleetctl get hosts`
### What did you expect to see?
A list of the hosts
### What did you see instead?
`could not list hosts: decode list hosts response: unexpected EOF`

### What did you do?
Opened the page and looked for my hosts
### What did you expect to see?
A list of the hosts
### What did you see instead?
The number of hosts that are online is ~3000 but the main screen shows the "It's kinda lonely in here" image.

My theory is that somewhere in the code for getting the number of hosts there is a marshaling error. We've been adding hosts to osquery and I wonder if one of the hostnames has a character that isn't expected and it's throwing an error.

**Comment by zwass** [comment] 2020-10-08 18:37
Can you upgrade to the latest release and let us know if this is still a problem?

**Comment by nyanshak** [comment] 2020-10-09 20:21
I tried replicating this by using https://github.com/dactivllc/osquery-perf with a large number of hosts and wasn't able to reproduce.

I figured it might be a specific weird host name, so I modified the script above to create hosts with hostnames out of [The Big List of Naughty Strings](https://github.com/minimaxir/big-list-of-naughty-strings/blob/master/blns.txt). This was pretty entertaining (seeing lots of emojis, unicode, and weird strings as hostnames) but I couldn't reproduce the issue you were seeing, @ccombs-sqsp.

**Comment by ccombs-sqsp** [comment] 2020-10-09 20:39
Gotcha, I'll probably just upgrade but it'll take a while, will update the thread if it's still an issue! Also, on the browser side I do sometimes get through and see the machines, so it doesn't seem to always error out?

**Comment by zwass** [comment] 2020-10-09 21:43
@nyanshak thank you for checking into that.

@ccombs-sqsp you mention ~3k hosts online. How many hosts are enrolled total?

Given everything mentioned here I would strongly wager that your issues are going to be resolved by the significant performance overhaul in Fleet 3.0.

**Closed as completed** 2020-10-09 21:59 UTC
Labels: Needs: Update
