### ISSUE TITLE
Saving logs on fleet clients machines

### ISSUE THREAD

**Issue by epifanoviv** [kolide/fleet#2340] opened 2020-10-28 07:48 UTC
fleet - version 3.1.0
  branch:       HEAD
  revision:     c6ce648fef3bb39b6e604333ec47cff0e625ff8e
  build date:   2020-08-07T00:09:34Z
  build user:   zwass
  go version:   go1.14.4
Ubuntu 18.04

Hello!  Please help me with solving my problem.
I need to save logs locally on clients machines.
leetctl get options:
kind: option
spec:
config:
decorators:
load:
- SELECT uuid AS host_uuid FROM system_info;
- SELECT hostname AS hostname FROM system_info;
options:
disable_distributed: false
distributed_interval: 10
distributed_plugin: tls
distributed_tls_max_attempts: 3
logger_plugin: filesystem
pack_delimiter: /
overrides: {}

But i still get logs locally on fleet server.
If there is any way to put logs locally on the fleet clients?

**Comment by zwass** [comment] 2020-10-28 22:11
This is a dupe of #2328.

If you need further help troubleshooting, please join the osquery slack.

**Closed as completed by zwass** 2020-10-28 22:11 UTC
