### ISSUE TITLE
fleet not reading custom made osquery tables using ATC

### ISSUE THREAD

**Issue by anishvarghese** [kolide/fleet#1986] opened 2019-01-11 10:44 UTC
### What version of `fleet` are you using (`fleet version --full`)?
fleet - version 2.0.0
### What operating system are you using?
Ubuntu 16.04.4 LTS \n \l

### What did you do?

I Build custom osquery tables using ATC in remote machine, listed the generated tables along with other tables in the remote machine and inserted data to the tables also
https://blog.kolide.com/build-custom-osquery-tables-using-atc-ab112a30674c

### What did you expect to see?

Expecting the new tables i Kolide interface

### What did you see instead?

The tables are not listed in kolide, but tables are accessible from the host machine using osqueryi client

**Comment by zwass** [comment] 2019-01-11 14:17
Where are you expecting the tables in the Fleet interface? Perhaps your issue is a duplicate of https://github.com/kolide/fleet/issues/1876?

**Comment by anishvarghese** [comment] 2019-01-15 11:17
Yes @zwass I think its the duplicate. Let me know whether this support available soon on fleet ??

**Comment by zwass** [comment] 2019-01-16 20:31
Closing this to track the issue in #1876. I can see adding this functionality in Fleet but it will require the user to manually specify which additional table names are available.

**Closed as completed by zwass** 2019-01-16 20:31 UTC
